using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Elite.Generic;
using EliteJournalReader;
using Newtonsoft.Json.Linq;
using NUnit.Framework;

namespace Elite.Tests
{
    /// <summary>
    /// Elite\PropertyInspector\catalog.js, generated by Elite.CatalogGen at build time.
    /// </summary>
    [TestFixture]
    public class CatalogTests
    {
        private static readonly string[] FieldTypes = { "bool", "number", "text", "date", "enum" };

        private JObject catalog;
        private Dictionary<string, JArray> fields;     // full key -> [path, type, enum?]
        private Dictionary<string, JObject> groupOfKey; // full key -> group

        [OneTimeSetUp]
        public void Load()
        {
            catalog = TestData.GeneratedJs("catalog.js", "ELITE_CATALOG");
            fields = new Dictionary<string, JArray>(StringComparer.OrdinalIgnoreCase);
            groupOfKey = new Dictionary<string, JObject>(StringComparer.OrdinalIgnoreCase);
            foreach (JObject group in catalog["groups"])
            {
                foreach (JArray field in group["fields"])
                {
                    var key = (string)group["prefix"] + "." + (string)field[0];
                    fields[key] = field;
                    groupOfKey[key] = group;
                }
            }
        }

        private JArray Field(string key)
        {
            JArray field;
            Assert.That(fields.TryGetValue(key, out field), Is.True, "missing key " + key);
            return field;
        }

        [Test]
        public void EveryLibraryEvent_HasAGroup_ExceptTheSyntheticOne()
        {
            var prefixes = new HashSet<string>(catalog["groups"].Select(g => (string)g["prefix"]), StringComparer.OrdinalIgnoreCase);
            var eventNames = typeof(JournalEvent).Assembly.GetTypes()
                .Where(t => typeof(JournalEvent).IsAssignableFrom(t) && !t.IsAbstract && !t.IsGenericTypeDefinition)
                .SelectMany(t => ((JournalEvent)Activator.CreateInstance(t)).EventNames)
                .ToList();

            var missing = eventNames.Where(n => !n.StartsWith("MagicMau.") && !prefixes.Contains("journal." + n)).ToList();

            Assert.That(eventNames.Count, Is.GreaterThanOrEqualTo(249));
            Assert.That(missing, Is.Empty);
            Assert.That(prefixes.Any(p => p.Contains("MagicMau")), Is.False);
        }

        [Test]
        public void RealJournalKeys_AreAllInTheCatalog()
        {
            var missing = new List<string>();
            foreach (var line in TestData.JournalLines())
            {
                var evt = JObject.Parse(line);
                var keys = StoreKeys.FromJournalEvent(evt.Value<string>("event"), evt);
                missing.AddRange(keys.Keys.Where(k => !fields.ContainsKey(k)));
            }

            Assert.That(missing, Is.Empty);
        }

        [Test]
        public void StatusKeys_AreAllInTheCatalog()
        {
            var missing = new List<string>();
            foreach (var file in new[] { "status-menu.json", "status-vaisseau.json", "status-a-pied.json" })
                missing.AddRange(StoreKeys.FromStatus(TestData.Status(file)).Keys.Where(k => !fields.ContainsKey(k)));

            Assert.That(missing, Is.Empty);
        }

        [Test]
        public void ReferenceKeys_HaveTheExpectedType()
        {
            Assert.That((string)Field("journal.FSDJump.StarSystem")[1], Is.EqualTo("text"));
            Assert.That((string)Field("journal.FSDJump.JumpDist")[1], Is.EqualTo("number"));
            Assert.That((string)Field("journal.FSDJump.StarPos.#count")[1], Is.EqualTo("number"));
            Assert.That((string)Field("journal.FSDJump.timestamp")[1], Is.EqualTo("date"));
            Assert.That((string)Field("journal.Cargo.Inventory.#count")[1], Is.EqualTo("number"));
            Assert.That((string)Field("journal.FSSSignalDiscovered.SignalType")[1], Is.EqualTo("text"), "observed in real journals");
            Assert.That((string)Field("status.Flags.LandingGearDown")[1], Is.EqualTo("bool"));
            Assert.That((string)Field("status.Pips.Engine")[1], Is.EqualTo("number"));

            var planetClass = Field("journal.Scan.PlanetClass");
            Assert.That((string)planetClass[1], Is.EqualTo("enum"));
            Assert.That(catalog["enums"][(string)planetClass[2]].Values<string>(), Does.Contain("Metal rich body"));

            var guiFocus = Field("status.GuiFocus");
            Assert.That((string)guiFocus[1], Is.EqualTo("enum"));
            Assert.That(catalog["enums"][(string)guiFocus[2]].Values<string>(), Does.Contain("GalaxyMap"));

            var legalState = Field("status.LegalState");
            Assert.That(catalog["enums"][(string)legalState[2]].Values<string>(), Does.Contain("Wanted"));
        }

        [Test]
        public void OdysseyMarkers_AndGameSpelling()
        {
            Assert.That((bool)groupOfKey["status.Flags2.OnFoot"]["odyssey"], Is.True);
            Assert.That((bool)groupOfKey["status.Oxygen"]["odyssey"], Is.True);
            Assert.That((bool)groupOfKey["status.Fuel.FuelMain"]["odyssey"], Is.False);
            Assert.That((bool)groupOfKey["journal.Disembark.timestamp"]["odyssey"], Is.True);
            Assert.That((bool)groupOfKey["journal.FSDJump.timestamp"]["odyssey"], Is.False);

            var dropship = groupOfKey["journal.DropshipDeploy.timestamp"];
            Assert.That((string)dropship["prefix"], Is.EqualTo("journal.DropshipDeploy"), "the game's spelling, not the library's DropShipDeploy");
            Assert.That((bool)dropship["odyssey"], Is.True);
        }

        [Test]
        public void Integrity_CategoriesEnumsTypesIds()
        {
            var categories = catalog["categories"].Select(c => (string)c["id"]).ToList();
            var enums = (JObject)catalog["enums"];
            var groups = catalog["groups"].Cast<JObject>().ToList();

            Assert.That(categories, Is.Unique);
            Assert.That(groups.Select(g => (string)g["id"]), Is.Unique);
            Assert.That(catalog["categories"].Select(c => (string)c["label"]), Does.Contain("Déplacement & accostage"));

            foreach (var group in groups)
            {
                Assert.That(categories, Does.Contain((string)group["category"]), (string)group["id"]);
                foreach (JArray field in group["fields"])
                {
                    Assert.That(FieldTypes, Does.Contain((string)field[1]), (string)group["id"] + "." + field[0]);
                    if ((string)field[1] == "enum")
                        Assert.That(enums.ContainsKey((string)field[2]), Is.True, "enum " + field[2]);
                }
            }

            Assert.That(fields.Count, Is.GreaterThan(1500));
        }

        [Test]
        public void GeneratedFiles_AreAscii()
        {
            foreach (var file in new[] { "catalog.js", "commands.js" })
            {
                var bytes = File.ReadAllBytes(TestData.PathOf(file));
                Assert.That(bytes.All(b => b < 0x80), Is.True, file);
            }
        }
    }
}
