using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using BarRaider.SdTools;
using Elite.Buttons;
using EliteJournalReader;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Elite.Generic
{
    /// <summary>
    /// "Alarme" action (com.mhwlng.elite.eventalarm, cahier des charges §5.3, docs/L8-alarme.md, docs/L10-v3.md): shows
    /// the alert image and plays the alert sound of an alarm when a journal event of its type (optionally filtered on one
    /// of its fields) is written live. Events replayed at startup never trigger it (IsLive guard). Up to 4 alarms per
    /// key (v3.6, AlarmSet): only the active one counts. The alert ends after its duration, or at a key press when the
    /// duration is 0. A press acknowledges the displayed alert, then sends its command, shortcut and click sound (at rest:
    /// those of alarm 1). A key that is not displayed (other page, closed folder) does not exist: it misses the events.
    /// </summary>
    [PluginActionId("com.mhwlng.elite.eventalarm")]
    public class EventAlarmAction : EliteKeypadBase
    {
        // property names = JSON names of EventAlarm.html; defaults apply to keys created before the setting existed
        protected class PluginSettings
        {
            [JsonProperty(PropertyName = "event")] public string Event { get; set; } = "";
            [JsonProperty(PropertyName = "filterField")] public string FilterField { get; set; } = "";
            [JsonProperty(PropertyName = "filterOp")] public string FilterOp { get; set; } = "";
            [JsonProperty(PropertyName = "filterValue")] public string FilterValue { get; set; } = "";
            [JsonProperty(PropertyName = "duration")] public string Duration { get; set; } = "5";
            [FilenameProperty]
            [JsonProperty(PropertyName = "idleImage")] public string IdleImage { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "activeImage")] public string ActiveImage { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "alarmSound")] public string AlarmSound { get; set; } = "";
            [JsonProperty(PropertyName = "pressCommand")] public string PressCommand { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkey")] public string PressHotkey { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkeyText")] public string PressHotkeyText { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "clickSound")] public string ClickSound { get; set; } = "";

            // ---- alarms 2 to 4 (same names + alarm number, idleImage is common): generated by tools/make-generic-html.py
            // <generated-alarms-2-4>
            [JsonProperty(PropertyName = "event2")] public string Event2 { get; set; } = "";
            [JsonProperty(PropertyName = "filterField2")] public string FilterField2 { get; set; } = "";
            [JsonProperty(PropertyName = "filterOp2")] public string FilterOp2 { get; set; } = "";
            [JsonProperty(PropertyName = "filterValue2")] public string FilterValue2 { get; set; } = "";
            [JsonProperty(PropertyName = "duration2")] public string Duration2 { get; set; } = "5";
            [FilenameProperty]
            [JsonProperty(PropertyName = "activeImage2")] public string ActiveImage2 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "alarmSound2")] public string AlarmSound2 { get; set; } = "";
            [JsonProperty(PropertyName = "pressCommand2")] public string PressCommand2 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkey2")] public string PressHotkey2 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkeyText2")] public string PressHotkeyText2 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "clickSound2")] public string ClickSound2 { get; set; } = "";
            [JsonProperty(PropertyName = "event3")] public string Event3 { get; set; } = "";
            [JsonProperty(PropertyName = "filterField3")] public string FilterField3 { get; set; } = "";
            [JsonProperty(PropertyName = "filterOp3")] public string FilterOp3 { get; set; } = "";
            [JsonProperty(PropertyName = "filterValue3")] public string FilterValue3 { get; set; } = "";
            [JsonProperty(PropertyName = "duration3")] public string Duration3 { get; set; } = "5";
            [FilenameProperty]
            [JsonProperty(PropertyName = "activeImage3")] public string ActiveImage3 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "alarmSound3")] public string AlarmSound3 { get; set; } = "";
            [JsonProperty(PropertyName = "pressCommand3")] public string PressCommand3 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkey3")] public string PressHotkey3 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkeyText3")] public string PressHotkeyText3 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "clickSound3")] public string ClickSound3 { get; set; } = "";
            [JsonProperty(PropertyName = "event4")] public string Event4 { get; set; } = "";
            [JsonProperty(PropertyName = "filterField4")] public string FilterField4 { get; set; } = "";
            [JsonProperty(PropertyName = "filterOp4")] public string FilterOp4 { get; set; } = "";
            [JsonProperty(PropertyName = "filterValue4")] public string FilterValue4 { get; set; } = "";
            [JsonProperty(PropertyName = "duration4")] public string Duration4 { get; set; } = "5";
            [FilenameProperty]
            [JsonProperty(PropertyName = "activeImage4")] public string ActiveImage4 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "alarmSound4")] public string AlarmSound4 { get; set; } = "";
            [JsonProperty(PropertyName = "pressCommand4")] public string PressCommand4 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkey4")] public string PressHotkey4 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkeyText4")] public string PressHotkeyText4 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "clickSound4")] public string ClickSound4 { get; set; } = "";
            // </generated-alarms-2-4>
        }

        private readonly object sync = new object();
        private readonly KeyMedia media = new KeyMedia("EventAlarm");
        private PluginSettings settings = new PluginSettings();
        private AlarmSet alarms = AlarmSet.FromSettings(null);
        private string lastImage;
        private int? lastActive;
        private bool imageSent;
        private bool disposed;

        public EventAlarmAction(SDConnection connection, InitialPayload payload) : base(connection, payload)
        {
            try
            {
                var raw = payload.Settings ?? new JObject();
                settings = raw.Count == 0 ? new PluginSettings() : raw.ToObject<PluginSettings>();

                // saves the defaults of the settings added since the key was created
                Connection.SetSettingsAsync(JObject.FromObject(settings)).Wait();

                ApplySettings();
                EliteStore.JournalEventReceived += OnJournalEvent;
                Connection.OnSendToPlugin += OnSendToPlugin;
                Render(true);
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"EventAlarm: constructor failed: {ex}");
            }
        }

        public override void KeyPressed(KeyPayload payload)
        {
            try
            {
                AlarmConfig current;
                int? acknowledged;
                lock (sync)
                {
                    // only the displayed alarm counts; at rest, the command of alarm 1
                    acknowledged = alarms.Acknowledge(DateTime.UtcNow);
                    current = alarms.Config(acknowledged ?? 0);
                }

                // the alert is acknowledged before the command is sent (§5.3)
                if (acknowledged.HasValue)
                {
                    Logger.Instance.LogMessage(TracingLevel.INFO, $"EventAlarm[{current.Event}]: acknowledged");
                    Render(false);
                }

                KeyCommands.Send(Connection, current.Command, current.Hotkey, current.HotkeyText, $"EventAlarm[{current.Event}]");

                media.Play(current.ClickSound);
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"EventAlarm[{alarms?.Config(0).Event}]: key press failed: {ex}");
            }
        }

        public override void ReceivedSettings(ReceivedSettingsPayload payload)
        {
            try
            {
                BarRaider.SdTools.Tools.AutoPopulateSettings(settings, payload.Settings);
                ApplySettings();
                Connection.SetSettingsAsync(JObject.FromObject(settings)).Wait();
                Render(true);
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"EventAlarm: settings update failed: {ex}");
            }
        }

        /// <summary>
        /// About every second: the alert ends when its duration is over (redrawn only when the alert state changed).
        /// </summary>
        public override void OnTick()
        {
            base.OnTick();
            try
            {
                bool changed;
                lock (sync)
                    changed = imageSent && alarms.Active(DateTime.UtcNow) != lastActive;
                if (changed)
                    Render(false);
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"EventAlarm[{alarms?.Config(0).Event}]: tick failed: {ex}");
            }
        }

        public override void Dispose()
        {
            lock (sync)
                disposed = true;

            EliteStore.JournalEventReceived -= OnJournalEvent;
            Connection.OnSendToPlugin -= OnSendToPlugin;
            base.Dispose();
        }

        // background thread (journal watcher), for every journal line, replayed (IsLive false) or live
        private void OnJournalEvent(object sender, RawJournalEventArgs e)
        {
            try
            {
                var triggered = new List<AlarmConfig>();
                lock (sync)
                {
                    if (disposed)
                        return;
                    foreach (var index in alarms.Observe(e, DateTime.UtcNow))
                        triggered.Add(alarms.Config(index));
                }

                foreach (var current in triggered)
                {
                    Logger.Instance.LogMessage(TracingLevel.INFO, $"EventAlarm[{current.Event}]: triggered");
                    Alert(current);
                }
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"EventAlarm[{alarms?.Config(0).Event}]: event handling failed: {ex}");
            }
        }

        /// <summary>
        /// Property inspector: { alarmTest: true, alarmIndex: n } triggers alarm n (1 to 4) as a live event would
        /// ("Tester l'alarme" button);
        /// { genericValueRequest: key } asks for the current value of a key (the "i" panel: last event received).
        /// </summary>
        private void OnSendToPlugin(object sender, BarRaider.SdTools.Wrappers.SDEventReceivedEventArgs<BarRaider.SdTools.Events.SendToPlugin> e)
        {
            try
            {
                var payload = e?.Event?.Payload;
                if (payload == null)
                    return;

                if (payload["alarmTest"] != null)
                {
                    AlarmConfig current;
                    lock (sync)
                    {
                        if (disposed)
                            return;
                        int index = (payload["alarmIndex"] != null ? payload["alarmIndex"].Value<int>() : 1) - 1;
                        if (index < 0 || index >= alarms.Count)
                            index = 0;
                        current = alarms.Config(index);
                        alarms.Trigger(index, DateTime.UtcNow);
                    }

                    Logger.Instance.LogMessage(TracingLevel.INFO, $"EventAlarm[{current.Event}]: test from the property inspector");
                    Alert(current);
                    return;
                }

                var key = payload["genericValueRequest"];
                if (key != null)
                {
                    JToken value;
                    EliteStore.TryGet((string)key, out value);
                    var reply = ValueFormatter.DescribeCurrentValue((string)key, value, new ValueSettings(), DateTime.Now);
                    Watch(Connection.SendToPropertyInspectorAsync(reply), "SendToPropertyInspector");
                }
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"EventAlarm: property inspector request failed: {ex}");
            }
        }

        private void Alert(AlarmConfig current)
        {
            Render(false);

            // without an alert image the key would not change: the Stream Deck warning triangle shows the alert
            if (KeyMedia.ExistingFile(current.ActiveImage) == null)
                Watch(Connection.ShowAlert(), "ShowAlert");

            media.Play(current.AlarmSound);
        }

        private void ApplySettings()
        {
            var newAlarms = AlarmSet.FromSettings(JObject.FromObject(settings),
                (alarm, warning) => Logger.Instance.LogMessage(TracingLevel.WARN, $"EventAlarm[{settings.Event}] alarm {alarm}: {warning}"));

            lock (sync)
            {
                newAlarms.KeepStatesOf(alarms);
                alarms = newAlarms;
            }
        }

        /// <summary>
        /// Sends the image only when it changed (force: after creation or a settings change): alert image of the displayed
        /// alarm while an alert is active, idle image otherwise; the default image of the action when the file is missing.
        /// Nothing is awaited, so that the watcher threads are never blocked.
        /// </summary>
        private void Render(bool force)
        {
            lock (sync)
            {
                if (disposed)
                    return;

                var active = alarms.Active(DateTime.UtcNow);
                var image = KeyMedia.ExistingFile(active.HasValue ? alarms.Config(active.Value).ActiveImage : alarms.Config(0).IdleImage);
                lastActive = active;
                if (!force && imageSent && image == lastImage)
                    return;

                lastImage = image;
                imageSent = true;
                var base64 = image == null ? null : media.ImageBase64(image);
                if (base64 != null)
                    Watch(Connection.SetImageAsync(base64), "SetImage");
                else
                    Watch(Connection.SetDefaultImageAsync(), "SetDefaultImage");
            }
        }

        private void Watch(Task task, string what)
        {
            task.ContinueWith(t => Logger.Instance.LogMessage(TracingLevel.ERROR, $"EventAlarm[{alarms?.Config(0).Event}]: {what} failed: {t.Exception}"),
                TaskContinuationOptions.OnlyOnFaulted);
        }
    }
}
