using System;
using System.Collections.Generic;
using System.Linq;
using BarRaider.SdTools;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Elite.Generic
{
    /// <summary>
    /// "Graphique" action (com.mhwlng.elite.graph, v3.4, issue #2, docs/L10-v3.md): built like "Donnée" (views,
    /// gestures, text, command, shortcut, sound, displayed view), but the image is a graph drawn by the plugin instead
    /// of image files: horizontal bar, vertical bar, dial or curve (history of the key, History), with bounds given by
    /// numbers or keys and colours given by rules.
    /// </summary>
    [PluginActionId("com.mhwlng.elite.graph")]
    public class GraphAction : DataKeyActionBase<GraphAction.PluginSettings>
    {
        // property names = JSON names of Graph.html, generated by tools/make-generic-html.py (all views)
        public class PluginSettings : IDataKeySettings
        {
            // <generated-graph-settings>
            // ---- view 1
            [JsonProperty(PropertyName = "source")] public string Source { get; set; } = "";
            [JsonProperty(PropertyName = "prefix")] public string Prefix { get; set; } = "";
            [JsonProperty(PropertyName = "suffix")] public string Suffix { get; set; } = "";
            [JsonProperty(PropertyName = "decimals")] public string Decimals { get; set; } = "0";
            [JsonProperty(PropertyName = "scale")] public string Scale { get; set; } = "1";
            [JsonProperty(PropertyName = "offset")] public string Offset { get; set; } = "0";
            [JsonProperty(PropertyName = "compact")] public bool Compact { get; set; }
            [JsonProperty(PropertyName = "showText")] public bool ShowText { get; set; } = true;
            [JsonProperty(PropertyName = "drawText")] public bool DrawText { get; set; }
            [JsonProperty(PropertyName = "fontSize")] public string FontSize { get; set; } = "18";
            [JsonProperty(PropertyName = "fontName")] public string FontName { get; set; } = TextStyle.DefaultFont;
            [JsonProperty(PropertyName = "fontColor")] public string FontColor { get; set; } = TextStyle.DefaultColor;
            [JsonProperty(PropertyName = "fontBold")] public bool FontBold { get; set; }
            [JsonProperty(PropertyName = "textPosition")] public string TextPosition { get; set; } = "top";
            [JsonProperty(PropertyName = "textWrap")] public bool TextWrap { get; set; } = true;
            [JsonProperty(PropertyName = "textFit")] public bool TextFit { get; set; } = true;
            [JsonProperty(PropertyName = "graphType")] public string GraphType { get; set; } = "hbar";
            [JsonProperty(PropertyName = "graphMin")] public string GraphMin { get; set; } = "0";
            [JsonProperty(PropertyName = "graphMax")] public string GraphMax { get; set; } = "100";
            [JsonProperty(PropertyName = "graphColor")] public string GraphColor { get; set; } = GraphConfig.DefaultColor;
            [JsonProperty(PropertyName = "colorRule1Op")] public string ColorRule1Op { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule1Value")] public string ColorRule1Value { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule1Color")] public string ColorRule1Color { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "colorRule2Op")] public string ColorRule2Op { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule2Value")] public string ColorRule2Value { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule2Color")] public string ColorRule2Color { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "colorRule3Op")] public string ColorRule3Op { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule3Value")] public string ColorRule3Value { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule3Color")] public string ColorRule3Color { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "colorRule4Op")] public string ColorRule4Op { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule4Value")] public string ColorRule4Value { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule4Color")] public string ColorRule4Color { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "curvePoints")] public string CurvePoints { get; set; } = "60";
            [JsonProperty(PropertyName = "curveInterval")] public string CurveInterval { get; set; } = "5";
            [JsonProperty(PropertyName = "pressCommand")] public string PressCommand { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkey")] public string PressHotkey { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkeyText")] public string PressHotkeyText { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "clickSound")] public string ClickSound { get; set; } = "";
            // ---- view 2
            [JsonProperty(PropertyName = "source2")] public string Source2 { get; set; } = "";
            [JsonProperty(PropertyName = "prefix2")] public string Prefix2 { get; set; } = "";
            [JsonProperty(PropertyName = "suffix2")] public string Suffix2 { get; set; } = "";
            [JsonProperty(PropertyName = "decimals2")] public string Decimals2 { get; set; } = "0";
            [JsonProperty(PropertyName = "scale2")] public string Scale2 { get; set; } = "1";
            [JsonProperty(PropertyName = "offset2")] public string Offset2 { get; set; } = "0";
            [JsonProperty(PropertyName = "compact2")] public bool Compact2 { get; set; }
            [JsonProperty(PropertyName = "showText2")] public bool ShowText2 { get; set; } = true;
            [JsonProperty(PropertyName = "drawText2")] public bool DrawText2 { get; set; }
            [JsonProperty(PropertyName = "fontSize2")] public string FontSize2 { get; set; } = "18";
            [JsonProperty(PropertyName = "fontName2")] public string FontName2 { get; set; } = TextStyle.DefaultFont;
            [JsonProperty(PropertyName = "fontColor2")] public string FontColor2 { get; set; } = TextStyle.DefaultColor;
            [JsonProperty(PropertyName = "fontBold2")] public bool FontBold2 { get; set; }
            [JsonProperty(PropertyName = "textPosition2")] public string TextPosition2 { get; set; } = "top";
            [JsonProperty(PropertyName = "textWrap2")] public bool TextWrap2 { get; set; } = true;
            [JsonProperty(PropertyName = "textFit2")] public bool TextFit2 { get; set; } = true;
            [JsonProperty(PropertyName = "graphType2")] public string GraphType2 { get; set; } = "hbar";
            [JsonProperty(PropertyName = "graphMin2")] public string GraphMin2 { get; set; } = "0";
            [JsonProperty(PropertyName = "graphMax2")] public string GraphMax2 { get; set; } = "100";
            [JsonProperty(PropertyName = "graphColor2")] public string GraphColor2 { get; set; } = GraphConfig.DefaultColor;
            [JsonProperty(PropertyName = "colorRule1Op2")] public string ColorRule1Op2 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule1Value2")] public string ColorRule1Value2 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule1Color2")] public string ColorRule1Color2 { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "colorRule2Op2")] public string ColorRule2Op2 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule2Value2")] public string ColorRule2Value2 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule2Color2")] public string ColorRule2Color2 { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "colorRule3Op2")] public string ColorRule3Op2 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule3Value2")] public string ColorRule3Value2 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule3Color2")] public string ColorRule3Color2 { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "colorRule4Op2")] public string ColorRule4Op2 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule4Value2")] public string ColorRule4Value2 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule4Color2")] public string ColorRule4Color2 { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "curvePoints2")] public string CurvePoints2 { get; set; } = "60";
            [JsonProperty(PropertyName = "curveInterval2")] public string CurveInterval2 { get; set; } = "5";
            [JsonProperty(PropertyName = "pressCommand2")] public string PressCommand2 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkey2")] public string PressHotkey2 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkeyText2")] public string PressHotkeyText2 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "clickSound2")] public string ClickSound2 { get; set; } = "";
            // ---- view 3
            [JsonProperty(PropertyName = "source3")] public string Source3 { get; set; } = "";
            [JsonProperty(PropertyName = "prefix3")] public string Prefix3 { get; set; } = "";
            [JsonProperty(PropertyName = "suffix3")] public string Suffix3 { get; set; } = "";
            [JsonProperty(PropertyName = "decimals3")] public string Decimals3 { get; set; } = "0";
            [JsonProperty(PropertyName = "scale3")] public string Scale3 { get; set; } = "1";
            [JsonProperty(PropertyName = "offset3")] public string Offset3 { get; set; } = "0";
            [JsonProperty(PropertyName = "compact3")] public bool Compact3 { get; set; }
            [JsonProperty(PropertyName = "showText3")] public bool ShowText3 { get; set; } = true;
            [JsonProperty(PropertyName = "drawText3")] public bool DrawText3 { get; set; }
            [JsonProperty(PropertyName = "fontSize3")] public string FontSize3 { get; set; } = "18";
            [JsonProperty(PropertyName = "fontName3")] public string FontName3 { get; set; } = TextStyle.DefaultFont;
            [JsonProperty(PropertyName = "fontColor3")] public string FontColor3 { get; set; } = TextStyle.DefaultColor;
            [JsonProperty(PropertyName = "fontBold3")] public bool FontBold3 { get; set; }
            [JsonProperty(PropertyName = "textPosition3")] public string TextPosition3 { get; set; } = "top";
            [JsonProperty(PropertyName = "textWrap3")] public bool TextWrap3 { get; set; } = true;
            [JsonProperty(PropertyName = "textFit3")] public bool TextFit3 { get; set; } = true;
            [JsonProperty(PropertyName = "graphType3")] public string GraphType3 { get; set; } = "hbar";
            [JsonProperty(PropertyName = "graphMin3")] public string GraphMin3 { get; set; } = "0";
            [JsonProperty(PropertyName = "graphMax3")] public string GraphMax3 { get; set; } = "100";
            [JsonProperty(PropertyName = "graphColor3")] public string GraphColor3 { get; set; } = GraphConfig.DefaultColor;
            [JsonProperty(PropertyName = "colorRule1Op3")] public string ColorRule1Op3 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule1Value3")] public string ColorRule1Value3 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule1Color3")] public string ColorRule1Color3 { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "colorRule2Op3")] public string ColorRule2Op3 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule2Value3")] public string ColorRule2Value3 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule2Color3")] public string ColorRule2Color3 { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "colorRule3Op3")] public string ColorRule3Op3 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule3Value3")] public string ColorRule3Value3 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule3Color3")] public string ColorRule3Color3 { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "colorRule4Op3")] public string ColorRule4Op3 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule4Value3")] public string ColorRule4Value3 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule4Color3")] public string ColorRule4Color3 { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "curvePoints3")] public string CurvePoints3 { get; set; } = "60";
            [JsonProperty(PropertyName = "curveInterval3")] public string CurveInterval3 { get; set; } = "5";
            [JsonProperty(PropertyName = "pressCommand3")] public string PressCommand3 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkey3")] public string PressHotkey3 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkeyText3")] public string PressHotkeyText3 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "clickSound3")] public string ClickSound3 { get; set; } = "";
            // ---- view 4
            [JsonProperty(PropertyName = "source4")] public string Source4 { get; set; } = "";
            [JsonProperty(PropertyName = "prefix4")] public string Prefix4 { get; set; } = "";
            [JsonProperty(PropertyName = "suffix4")] public string Suffix4 { get; set; } = "";
            [JsonProperty(PropertyName = "decimals4")] public string Decimals4 { get; set; } = "0";
            [JsonProperty(PropertyName = "scale4")] public string Scale4 { get; set; } = "1";
            [JsonProperty(PropertyName = "offset4")] public string Offset4 { get; set; } = "0";
            [JsonProperty(PropertyName = "compact4")] public bool Compact4 { get; set; }
            [JsonProperty(PropertyName = "showText4")] public bool ShowText4 { get; set; } = true;
            [JsonProperty(PropertyName = "drawText4")] public bool DrawText4 { get; set; }
            [JsonProperty(PropertyName = "fontSize4")] public string FontSize4 { get; set; } = "18";
            [JsonProperty(PropertyName = "fontName4")] public string FontName4 { get; set; } = TextStyle.DefaultFont;
            [JsonProperty(PropertyName = "fontColor4")] public string FontColor4 { get; set; } = TextStyle.DefaultColor;
            [JsonProperty(PropertyName = "fontBold4")] public bool FontBold4 { get; set; }
            [JsonProperty(PropertyName = "textPosition4")] public string TextPosition4 { get; set; } = "top";
            [JsonProperty(PropertyName = "textWrap4")] public bool TextWrap4 { get; set; } = true;
            [JsonProperty(PropertyName = "textFit4")] public bool TextFit4 { get; set; } = true;
            [JsonProperty(PropertyName = "graphType4")] public string GraphType4 { get; set; } = "hbar";
            [JsonProperty(PropertyName = "graphMin4")] public string GraphMin4 { get; set; } = "0";
            [JsonProperty(PropertyName = "graphMax4")] public string GraphMax4 { get; set; } = "100";
            [JsonProperty(PropertyName = "graphColor4")] public string GraphColor4 { get; set; } = GraphConfig.DefaultColor;
            [JsonProperty(PropertyName = "colorRule1Op4")] public string ColorRule1Op4 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule1Value4")] public string ColorRule1Value4 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule1Color4")] public string ColorRule1Color4 { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "colorRule2Op4")] public string ColorRule2Op4 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule2Value4")] public string ColorRule2Value4 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule2Color4")] public string ColorRule2Color4 { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "colorRule3Op4")] public string ColorRule3Op4 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule3Value4")] public string ColorRule3Value4 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule3Color4")] public string ColorRule3Color4 { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "colorRule4Op4")] public string ColorRule4Op4 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule4Value4")] public string ColorRule4Value4 { get; set; } = "";
            [JsonProperty(PropertyName = "colorRule4Color4")] public string ColorRule4Color4 { get; set; } = GraphConfig.DefaultRuleColor;
            [JsonProperty(PropertyName = "curvePoints4")] public string CurvePoints4 { get; set; } = "60";
            [JsonProperty(PropertyName = "curveInterval4")] public string CurveInterval4 { get; set; } = "5";
            [JsonProperty(PropertyName = "pressCommand4")] public string PressCommand4 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkey4")] public string PressHotkey4 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkeyText4")] public string PressHotkeyText4 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "clickSound4")] public string ClickSound4 { get; set; } = "";
            // ---- whole key
            [JsonProperty(PropertyName = "emptyText")] public string EmptyText { get; set; } = ValueSettings.DefaultEmptyText;
            [JsonProperty(PropertyName = "pressMode")] public string PressMode { get; set; } = PressGesture.ShortActLongViewName;
            // </generated-graph-settings>

            // ---- saved by the plugin, not by the page: displayed view (1 to 4)
            [JsonProperty(PropertyName = "currentView")] public int CurrentView { get; set; } = 1;
        }

        private Dictionary<int, GraphView> graphs = new Dictionary<int, GraphView>();

        public GraphAction(SDConnection connection, InitialPayload payload) : base(connection, payload, "GraphAction")
        {
            History.Changed += OnHistoryChanged;
        }

        public override void Dispose()
        {
            History.Changed -= OnHistoryChanged;
            base.Dispose();
        }

        protected override void SettingsApplied(JObject json)
        {
            var newGraphs = new Dictionary<int, GraphView>();
            var now = DateTime.UtcNow;
            for (int v = 1; v <= DataKeyConfig.MaxViews; v++)
            {
                var suffix = v == 1 ? "" : v.ToString();
                var graph = GraphConfig.Parse(json, suffix);
                newGraphs[v] = graph;

                // the history of a curve is kept even while the key is not displayed
                var source = ((string)json["source" + suffix] ?? "").Trim();
                if (graph.Type == GraphType.Curve && source.Length > 0)
                    History.Track(source, graph.CurveInterval, now);
            }

            lock (renderLock)
                graphs = newGraphs;
        }

        protected override IEnumerable<string> WatchedKeys(DataView view)
        {
            yield return view.Source;
            GraphView graph;
            if (graphs.TryGetValue(view.Number, out graph))
            {
                foreach (var key in GraphConfig.BoundKeys(graph))
                    yield return key;
            }
        }

        // timer thread of History
        private void OnHistoryChanged(string id)
        {
            try
            {
                bool concerned;
                lock (renderLock)
                {
                    if (config == null)
                        return;
                    var view = CurrentView();
                    GraphView graph;
                    concerned = graphs.TryGetValue(view.Number, out graph) && graph.Type == GraphType.Curve
                        && string.Equals(History.Id(view.Source, graph.CurveInterval), id, StringComparison.OrdinalIgnoreCase);
                }

                if (concerned)
                    Render(false);
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"{Owner}: history refresh failed: {ex}");
            }
        }

        // caller holds renderLock
        protected override KeyImage BuildImage(DataView view, string drawnText)
        {
            GraphView graph;
            if (!graphs.TryGetValue(view.Number, out graph))
                graph = new GraphView();

            var tested = ImageRules.Displayed(Read(view.Source), view.Display);
            var value = History.Number(tested);
            var min = GraphConfig.Bound(graph.Min, Read, view.Display);
            var max = GraphConfig.Bound(graph.Max, Read, view.Display);
            var color = GraphConfig.ColorOf(graph, tested);

            List<double?> points = null;
            if (graph.Type == GraphType.Curve)
            {
                // history of raw values, shown in the displayed unit
                var history = History.Points(view.Source, graph.CurveInterval);
                points = history.Skip(Math.Max(0, history.Count - graph.CurvePoints))
                    .Select(p => p.HasValue ? p.Value * view.Display.Scale + view.Display.Offset : (double?)null)
                    .ToList();
            }

            var fraction = GraphConfig.Fraction(value, min, max);
            var style = view.Text;
            var signature = string.Join("|", "graph", graph.Signature, GraphConfig.Format(fraction), GraphConfig.Format(min), GraphConfig.Format(max),
                color, points == null ? "" : string.Join(",", points.Select(GraphConfig.Format)), drawnText ?? "", style.Signature);

            var type = graph.Type;
            return new KeyImage(signature, () => KeyRenderer.RenderBase64(null,
                g => GraphRenderer.Draw(g, type, fraction, color, points, min, max), drawnText, style));
        }
    }
}
