using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using BarRaider.SdTools;
using Elite.Buttons;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Elite.Generic
{
    /// <summary>
    /// "Donnée" action (UUID kept from L3: com.mhwlng.elite.value), see docs/L5-tiroir.md.
    /// Up to 4 views ("drawer"); each view has its data and text, its icon (rules), its command and its sound.
    /// Gestures: by default a short press acts (command of the displayed view) and a long press (0.5 s) shows the next view.
    /// Redrawn only when one of its keys changes, and only what changed is sent (§4.5).
    /// </summary>
    [PluginActionId("com.mhwlng.elite.value")]
    public class ValueAction : EliteKeypadBase
    {
        // property names = JSON names of Generic.html; defaults apply to keys created before the setting existed
        protected class PluginSettings
        {
            // ---- view 1 (names of L3 / L4)
            [JsonProperty(PropertyName = "source")] public string Source { get; set; } = "";
            [JsonProperty(PropertyName = "prefix")] public string Prefix { get; set; } = "";
            [JsonProperty(PropertyName = "suffix")] public string Suffix { get; set; } = "";
            [JsonProperty(PropertyName = "decimals")] public string Decimals { get; set; } = "0";
            [JsonProperty(PropertyName = "scale")] public string Scale { get; set; } = "1";
            [JsonProperty(PropertyName = "offset")] public string Offset { get; set; } = "0";
            [JsonProperty(PropertyName = "compact")] public bool Compact { get; set; }
            [JsonProperty(PropertyName = "showText")] public bool ShowText { get; set; } = true;
            [FilenameProperty]
            [JsonProperty(PropertyName = "backgroundImage")] public string BackgroundImage { get; set; } = "";
            [JsonProperty(PropertyName = "rule1Op")] public string Rule1Op { get; set; } = "";
            [JsonProperty(PropertyName = "rule1Value")] public string Rule1Value { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule1Image")] public string Rule1Image { get; set; } = "";
            [JsonProperty(PropertyName = "rule2Op")] public string Rule2Op { get; set; } = "";
            [JsonProperty(PropertyName = "rule2Value")] public string Rule2Value { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule2Image")] public string Rule2Image { get; set; } = "";
            [JsonProperty(PropertyName = "rule3Op")] public string Rule3Op { get; set; } = "";
            [JsonProperty(PropertyName = "rule3Value")] public string Rule3Value { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule3Image")] public string Rule3Image { get; set; } = "";
            [JsonProperty(PropertyName = "rule4Op")] public string Rule4Op { get; set; } = "";
            [JsonProperty(PropertyName = "rule4Value")] public string Rule4Value { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule4Image")] public string Rule4Image { get; set; } = "";
            [JsonProperty(PropertyName = "pressCommand")] public string PressCommand { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkey")] public string PressHotkey { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkeyText")] public string PressHotkeyText { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "clickSound")] public string ClickSound { get; set; } = "";

            // ---- views 2 to 4 (same names + view number): generated by tools/make-generic-html.py, do not edit by hand
            // <generated-views-2-4>
            [JsonProperty(PropertyName = "source2")] public string Source2 { get; set; } = "";
            [JsonProperty(PropertyName = "prefix2")] public string Prefix2 { get; set; } = "";
            [JsonProperty(PropertyName = "suffix2")] public string Suffix2 { get; set; } = "";
            [JsonProperty(PropertyName = "decimals2")] public string Decimals2 { get; set; } = "0";
            [JsonProperty(PropertyName = "scale2")] public string Scale2 { get; set; } = "1";
            [JsonProperty(PropertyName = "offset2")] public string Offset2 { get; set; } = "0";
            [JsonProperty(PropertyName = "compact2")] public bool Compact2 { get; set; }
            [JsonProperty(PropertyName = "showText2")] public bool ShowText2 { get; set; } = true;
            [FilenameProperty]
            [JsonProperty(PropertyName = "backgroundImage2")] public string BackgroundImage2 { get; set; } = "";
            [JsonProperty(PropertyName = "rule1Op2")] public string Rule1Op2 { get; set; } = "";
            [JsonProperty(PropertyName = "rule1Value2")] public string Rule1Value2 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule1Image2")] public string Rule1Image2 { get; set; } = "";
            [JsonProperty(PropertyName = "rule2Op2")] public string Rule2Op2 { get; set; } = "";
            [JsonProperty(PropertyName = "rule2Value2")] public string Rule2Value2 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule2Image2")] public string Rule2Image2 { get; set; } = "";
            [JsonProperty(PropertyName = "rule3Op2")] public string Rule3Op2 { get; set; } = "";
            [JsonProperty(PropertyName = "rule3Value2")] public string Rule3Value2 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule3Image2")] public string Rule3Image2 { get; set; } = "";
            [JsonProperty(PropertyName = "rule4Op2")] public string Rule4Op2 { get; set; } = "";
            [JsonProperty(PropertyName = "rule4Value2")] public string Rule4Value2 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule4Image2")] public string Rule4Image2 { get; set; } = "";
            [JsonProperty(PropertyName = "pressCommand2")] public string PressCommand2 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkey2")] public string PressHotkey2 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkeyText2")] public string PressHotkeyText2 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "clickSound2")] public string ClickSound2 { get; set; } = "";
            [JsonProperty(PropertyName = "source3")] public string Source3 { get; set; } = "";
            [JsonProperty(PropertyName = "prefix3")] public string Prefix3 { get; set; } = "";
            [JsonProperty(PropertyName = "suffix3")] public string Suffix3 { get; set; } = "";
            [JsonProperty(PropertyName = "decimals3")] public string Decimals3 { get; set; } = "0";
            [JsonProperty(PropertyName = "scale3")] public string Scale3 { get; set; } = "1";
            [JsonProperty(PropertyName = "offset3")] public string Offset3 { get; set; } = "0";
            [JsonProperty(PropertyName = "compact3")] public bool Compact3 { get; set; }
            [JsonProperty(PropertyName = "showText3")] public bool ShowText3 { get; set; } = true;
            [FilenameProperty]
            [JsonProperty(PropertyName = "backgroundImage3")] public string BackgroundImage3 { get; set; } = "";
            [JsonProperty(PropertyName = "rule1Op3")] public string Rule1Op3 { get; set; } = "";
            [JsonProperty(PropertyName = "rule1Value3")] public string Rule1Value3 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule1Image3")] public string Rule1Image3 { get; set; } = "";
            [JsonProperty(PropertyName = "rule2Op3")] public string Rule2Op3 { get; set; } = "";
            [JsonProperty(PropertyName = "rule2Value3")] public string Rule2Value3 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule2Image3")] public string Rule2Image3 { get; set; } = "";
            [JsonProperty(PropertyName = "rule3Op3")] public string Rule3Op3 { get; set; } = "";
            [JsonProperty(PropertyName = "rule3Value3")] public string Rule3Value3 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule3Image3")] public string Rule3Image3 { get; set; } = "";
            [JsonProperty(PropertyName = "rule4Op3")] public string Rule4Op3 { get; set; } = "";
            [JsonProperty(PropertyName = "rule4Value3")] public string Rule4Value3 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule4Image3")] public string Rule4Image3 { get; set; } = "";
            [JsonProperty(PropertyName = "pressCommand3")] public string PressCommand3 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkey3")] public string PressHotkey3 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkeyText3")] public string PressHotkeyText3 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "clickSound3")] public string ClickSound3 { get; set; } = "";
            [JsonProperty(PropertyName = "source4")] public string Source4 { get; set; } = "";
            [JsonProperty(PropertyName = "prefix4")] public string Prefix4 { get; set; } = "";
            [JsonProperty(PropertyName = "suffix4")] public string Suffix4 { get; set; } = "";
            [JsonProperty(PropertyName = "decimals4")] public string Decimals4 { get; set; } = "0";
            [JsonProperty(PropertyName = "scale4")] public string Scale4 { get; set; } = "1";
            [JsonProperty(PropertyName = "offset4")] public string Offset4 { get; set; } = "0";
            [JsonProperty(PropertyName = "compact4")] public bool Compact4 { get; set; }
            [JsonProperty(PropertyName = "showText4")] public bool ShowText4 { get; set; } = true;
            [FilenameProperty]
            [JsonProperty(PropertyName = "backgroundImage4")] public string BackgroundImage4 { get; set; } = "";
            [JsonProperty(PropertyName = "rule1Op4")] public string Rule1Op4 { get; set; } = "";
            [JsonProperty(PropertyName = "rule1Value4")] public string Rule1Value4 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule1Image4")] public string Rule1Image4 { get; set; } = "";
            [JsonProperty(PropertyName = "rule2Op4")] public string Rule2Op4 { get; set; } = "";
            [JsonProperty(PropertyName = "rule2Value4")] public string Rule2Value4 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule2Image4")] public string Rule2Image4 { get; set; } = "";
            [JsonProperty(PropertyName = "rule3Op4")] public string Rule3Op4 { get; set; } = "";
            [JsonProperty(PropertyName = "rule3Value4")] public string Rule3Value4 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule3Image4")] public string Rule3Image4 { get; set; } = "";
            [JsonProperty(PropertyName = "rule4Op4")] public string Rule4Op4 { get; set; } = "";
            [JsonProperty(PropertyName = "rule4Value4")] public string Rule4Value4 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "rule4Image4")] public string Rule4Image4 { get; set; } = "";
            [JsonProperty(PropertyName = "pressCommand4")] public string PressCommand4 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkey4")] public string PressHotkey4 { get; set; } = "";
            [JsonProperty(PropertyName = "pressHotkeyText4")] public string PressHotkeyText4 { get; set; } = "";
            [FilenameProperty]
            [JsonProperty(PropertyName = "clickSound4")] public string ClickSound4 { get; set; } = "";
            // </generated-views-2-4>

            // ---- whole key
            [JsonProperty(PropertyName = "emptyText")] public string EmptyText { get; set; } = ValueSettings.DefaultEmptyText;
            [JsonProperty(PropertyName = "pressMode")] public string PressMode { get; set; } = PressGesture.ShortActLongViewName;

            // ---- saved by the plugin, not by the page: displayed view (1 to 4), kept when the key disappears (folder...)
            [JsonProperty(PropertyName = "currentView")] public int CurrentView { get; set; } = 1;
        }

        private const string NoTitle = "\u0000no title";

        private readonly object renderLock = new object();
        private readonly Dictionary<string, string> imageCache = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        private readonly Dictionary<string, CachedSound> soundCache = new Dictionary<string, CachedSound>(StringComparer.OrdinalIgnoreCase);
        private PluginSettings settings;
        private DataKeyConfig config;
        private Dictionary<DataView, List<ImageRule>> validRules = new Dictionary<DataView, List<ImageRule>>();
        private int viewIndex;
        private string lastTitle;
        private string lastImage;
        private bool imageSent;
        private bool disposed;

        // key press: the long action fires after LongPressMilliseconds, the short one on release
        private Timer longPressTimer;
        private bool keyDown;
        private bool longPressDone;

        public ValueAction(SDConnection connection, InitialPayload payload) : base(connection, payload)
        {
            try
            {
                var raw = payload.Settings ?? new JObject();
                InheritShowText(raw);
                settings = raw.Count == 0 ? new PluginSettings() : raw.ToObject<PluginSettings>();

                // saves the defaults of the settings added since the key was created
                Connection.SetSettingsAsync(JObject.FromObject(settings)).Wait();

                ApplySettings();
                EliteStore.DataChanged += OnDataChanged;
                Connection.OnSendToPlugin += OnSendToPlugin;
                Render(true);
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"ValueAction: constructor failed: {ex}");
            }
        }

        public override void KeyPressed(KeyPayload payload)
        {
            try
            {
                lock (renderLock)
                {
                    keyDown = true;
                    longPressDone = false;
                    longPressTimer?.Dispose();
                    longPressTimer = new Timer(OnLongPress, null, PressGesture.LongPressMilliseconds, Timeout.Infinite);
                }
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"ValueAction[{config?.MainView.Source}]: key press failed: {ex}");
            }
        }

        public override void KeyReleased(KeyPayload payload)
        {
            try
            {
                bool shortPress;
                lock (renderLock)
                {
                    longPressTimer?.Dispose();
                    longPressTimer = null;
                    shortPress = keyDown && !longPressDone;
                    keyDown = false;
                }

                if (shortPress)
                    Perform(false);
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"ValueAction[{config?.MainView.Source}]: key release failed: {ex}");
            }
        }

        public override void ReceivedSettings(ReceivedSettingsPayload payload)
        {
            try
            {
                InheritShowText(payload.Settings);
                BarRaider.SdTools.Tools.AutoPopulateSettings(settings, payload.Settings);
                ApplySettings();
                Connection.SetSettingsAsync(JObject.FromObject(settings)).Wait();
                Render(true);
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"ValueAction: settings update failed: {ex}");
            }
        }

        public override void Dispose()
        {
            lock (renderLock)
            {
                disposed = true;
                longPressTimer?.Dispose();
                longPressTimer = null;
            }

            EliteStore.DataChanged -= OnDataChanged;
            Connection.OnSendToPlugin -= OnSendToPlugin;
            base.Dispose();
        }

        /// <summary>
        /// Keys created before L5 have no showText2..4: those views keep the choice of view 1 (as in L4).
        /// </summary>
        private static void InheritShowText(JObject raw)
        {
            if (raw == null)
                return;

            var main = raw["showText"];
            for (int i = 2; i <= DataKeyConfig.MaxViews; i++)
            {
                var name = "showText" + i;
                if (raw[name] == null || raw[name].Type == JTokenType.Null)
                    raw[name] = main == null || main.Type == JTokenType.Null ? new JValue(true) : main.DeepClone();
            }
        }

        // timer thread
        private void OnLongPress(object state)
        {
            try
            {
                lock (renderLock)
                {
                    if (!keyDown || longPressDone || disposed)
                        return;
                    longPressDone = true;
                }

                Perform(true);
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"ValueAction[{config?.MainView.Source}]: long press failed: {ex}");
            }
        }

        private void Perform(bool isLongPress)
        {
            DataView view;
            PressOutcome outcome;
            JObject savedSettings = null;
            lock (renderLock)
            {
                if (config == null)
                    return;
                outcome = PressGesture.Resolve(isLongPress, config.PressMode, config.Views.Count);
                if (outcome == PressOutcome.NextView)
                {
                    viewIndex = (viewIndex + 1) % config.Views.Count;
                    // the key is recreated each time it appears again (folder, page...): the view is kept in its settings
                    settings.CurrentView = config.Views[viewIndex].Number;
                    savedSettings = JObject.FromObject(settings);
                }
                view = CurrentView();
            }

            if (outcome == PressOutcome.NextView)
            {
                Render(false);
                Watch(Connection.SetSettingsAsync(savedSettings), "SetSettings");
                return;
            }

            if (view.Command.Length > 0)
            {
                var blocked = CommandGuard.BlockReason(view.Command, EliteData.StatusData);
                if (blocked != null)
                {
                    // EliteKeys ignores it silently: the Stream Deck warning triangle says so
                    Logger.Instance.LogMessage(TracingLevel.INFO, $"ValueAction[{view.Source}]: {view.Command} ignored ({blocked})");
                    Watch(Connection.ShowAlert(), "ShowAlert");
                }
                else
                    EliteKeys.SendKeypress(view.Command);
            }

            if (view.Hotkey.Length > 0)
                Hotkey.Send(view.Hotkey, view.HotkeyText);

            var sound = Sound(view.Sound);
            if (sound != null)
                AudioPlaybackEngine.Instance.PlaySound(sound);
        }

        // background thread (status or journal watcher)
        /// <summary>
        /// "i" panel of the property inspector: { genericValueRequest: key, genericView: n } -> current value of the key,
        /// formatted with the settings of view n.
        /// </summary>
        private void OnSendToPlugin(object sender, BarRaider.SdTools.Wrappers.SDEventReceivedEventArgs<BarRaider.SdTools.Events.SendToPlugin> e)
        {
            try
            {
                var payload = e?.Event?.Payload;
                var key = payload?["genericValueRequest"];
                if (key == null)
                    return;

                int viewNumber = payload["genericView"] != null ? payload["genericView"].Value<int>() : 1;
                ValueSettings display;
                lock (renderLock)
                {
                    var view = config?.Views.FirstOrDefault(v => v.Number == viewNumber) ?? config?.MainView;
                    display = view != null ? view.Display : new ValueSettings();
                }

                var reply = ValueFormatter.DescribeCurrentValue((string)key, Read((string)key), display, DateTime.Now);
                Watch(Connection.SendToPropertyInspectorAsync(reply), "SendToPropertyInspector");
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"ValueAction: current value request failed: {ex}");
            }
        }

        private void OnDataChanged(IReadOnlyCollection<string> changedKeys)
        {
            try
            {
                DataView view, iconView;
                lock (renderLock)
                {
                    if (config == null)
                        return;
                    view = CurrentView();
                    iconView = config.IconViewOf(view);
                }

                if ((view.Source.Length > 0 && changedKeys.Contains(view.Source, StoreKeys.Comparer))
                    || (iconView.Source.Length > 0 && changedKeys.Contains(iconView.Source, StoreKeys.Comparer)))
                    Render(false);
            }
            catch (Exception ex)
            {
                Logger.Instance.LogMessage(TracingLevel.ERROR, $"ValueAction[{config?.MainView.Source}]: refresh failed: {ex}");
            }
        }

        private void ApplySettings()
        {
            var newConfig = DataKeyConfig.FromSettings(JObject.FromObject(settings),
                warning => Logger.Instance.LogMessage(TracingLevel.WARN, $"ValueAction[{settings.Source}]: {warning}"));

            // a rule whose image file does not exist is ignored
            var newRules = newConfig.Views.ToDictionary(
                v => v,
                v => v.Rules.Select(r => new ImageRule(r.Operator, r.Operand, ExistingFile(r.Image))).ToList());

            lock (renderLock)
            {
                config = newConfig;
                validRules = newRules;
                // saved displayed view (view 1 if it no longer exists)
                viewIndex = config.CurrentViewIndex;
                settings.CurrentView = CurrentView().Number;
            }
        }

        private DataView CurrentView()
        {
            return config.Views[Math.Min(viewIndex, config.Views.Count - 1)];
        }

        /// <summary>
        /// Sends the title and the image of the displayed view only when they changed (force: after creation or a
        /// settings change). Nothing is awaited, so that the watcher threads are never blocked.
        /// </summary>
        private void Render(bool force)
        {
            lock (renderLock)
            {
                if (disposed || config == null)
                    return;

                var view = CurrentView();
                var title = view.ShowText ? ValueFormatter.Format(Read(view.Source), view.Display, DateTime.Now) : NoTitle;
                if (force || title != lastTitle)
                {
                    lastTitle = title;
                    if (title == NoTitle)
                        Watch(Connection.SetTitleAsync(null), "SetTitle"); // the title typed in the Stream Deck software is shown
                    else
                    {
                        Logger.Instance.LogMessage(TracingLevel.DEBUG, $"Value[{view.Source}] view {view.Number} = {title.Replace("\n", "\\n")}");
                        Watch(Connection.SetTitleAsync(title), "SetTitle");
                    }
                }

                var iconView = config.IconViewOf(view);
                var image = ImageRules.Choose(Read(iconView.Source), iconView.Display, validRules[iconView]) ?? ExistingFile(iconView.DefaultImage);
                if (force || !imageSent || image != lastImage)
                {
                    lastImage = image;
                    imageSent = true;
                    var base64 = image == null ? null : ImageBase64(image);
                    if (base64 != null)
                        Watch(Connection.SetImageAsync(base64), "SetImage");
                    else
                        Watch(Connection.SetDefaultImageAsync(), "SetDefaultImage");
                }
            }
        }

        private static JToken Read(string key)
        {
            JToken value = null;
            if (!string.IsNullOrEmpty(key))
                EliteStore.TryGet(key, out value);
            return value;
        }

        private static string ExistingFile(string path)
        {
            return !string.IsNullOrWhiteSpace(path) && File.Exists(path) ? path : null;
        }

        private string ImageBase64(string path)
        {
            string base64;
            if (!imageCache.TryGetValue(path, out base64))
            {
                try
                {
                    base64 = Tools.FileToBase64(path, true);
                }
                catch (Exception ex)
                {
                    Logger.Instance.LogMessage(TracingLevel.WARN, $"ValueAction: cannot read image {path}: {ex.Message}");
                    base64 = null;
                }

                imageCache[path] = base64;
            }

            return base64;
        }

        private CachedSound Sound(string path)
        {
            if (ExistingFile(path) == null)
                return null;

            lock (soundCache)
            {
                CachedSound sound;
                if (!soundCache.TryGetValue(path, out sound))
                {
                    try
                    {
                        sound = new CachedSound(path);
                    }
                    catch (Exception ex)
                    {
                        Logger.Instance.LogMessage(TracingLevel.WARN, $"ValueAction: cannot load sound {path}: {ex.Message}");
                        sound = null;
                    }

                    soundCache[path] = sound;
                }

                return sound;
            }
        }

        private void Watch(Task task, string what)
        {
            task.ContinueWith(t => Logger.Instance.LogMessage(TracingLevel.ERROR, $"ValueAction[{config?.MainView.Source}]: {what} failed: {t.Exception}"),
                TaskContinuationOptions.OnlyOnFaulted);
        }
    }
}
