using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Elite.CatalogGen
{
    /// <summary>
    /// Generates Elite\PropertyInspector\catalog.js (every key the property inspector can offer) and commands.js
    /// (keyboard commands). Run at each build of this project, see Elite.CatalogGen.csproj and docs/L2-catalogue.md.
    ///   Elite.CatalogGen.exe generate &lt;repository root&gt;
    ///   Elite.CatalogGen.exe scan &lt;journal folder&gt; &lt;repository root&gt;   (rewrites observed-keys.txt)
    /// </summary>
    internal static class Program
    {
        private const int MinimumKeys = 1000;
        private const int MinimumCommands = 300;

        private static readonly JsonSerializerSettings JsonSettings = new JsonSerializerSettings
        {
            Formatting = Formatting.None,
            StringEscapeHandling = StringEscapeHandling.EscapeNonAscii, // ASCII-only files: no charset issue in the inspector
        };

        private static int Main(string[] args)
        {
            try
            {
                if (args.Length == 2 && args[0] == "generate")
                    return Generate(Path.GetFullPath(args[1]));
                if (args.Length == 3 && args[0] == "scan")
                    return Scan(args[1], Path.GetFullPath(args[2]));
                if (args.Length == 2 && args[0] == "descriptions")
                    return ExtractDescriptions(Path.GetFullPath(args[1]));

                Console.Error.WriteLine("usage: Elite.CatalogGen.exe generate <repository root> | scan <journal folder> <repository root> | descriptions <repository root>");
                return 2;
            }
            catch (Exception ex)
            {
                // "error CODE:" is shown as a build error by MSBuild
                Console.WriteLine("error CATGEN01: " + ex.Message);
                Console.Error.WriteLine(ex);
                return 1;
            }
        }

        private static int Generate(string root)
        {
            var catalog = ReflectionCatalog();

            var observedPath = Path.Combine(root, "Elite.CatalogGen", ObservedKeys.FileName);
            if (File.Exists(observedPath))
                ObservedKeys.Merge(catalog, File.ReadAllLines(observedPath));

            var descriptions = Descriptions.Load(Path.Combine(root, "Elite.CatalogGen", Descriptions.FrenchFile));
            var orphans = Descriptions.Merge(catalog, descriptions);
            if (orphans.Count > 0)
                Console.WriteLine("Elite.CatalogGen: " + orphans.Count + " description(s) without catalog key ignored: " + string.Join(", ", orphans.Take(5)));

            if (catalog.KeyCount < MinimumKeys)
                throw new InvalidOperationException("catalog: only " + catalog.KeyCount + " keys (expected at least " + MinimumKeys + ")");

            var commands = CommandList.Parse(File.ReadAllText(Path.Combine(root, "Elite", "Buttons", "EliteKeys.cs")));
            int commandCount = commands.Sum(g => g.Commands.Count);
            if (commandCount < MinimumCommands)
                throw new InvalidOperationException("commands: only " + commandCount + " (expected at least " + MinimumCommands + ")");

            var inspector = Path.Combine(root, "Elite", "PropertyInspector");
            bool catalogWritten = WriteIfChanged(Path.Combine(inspector, "catalog.js"), CatalogJs(catalog));
            bool commandsWritten = WriteIfChanged(Path.Combine(inspector, "commands.js"), CommandsJs(commands));

            Console.WriteLine("Elite.CatalogGen: catalog.js " + catalog.Groups.Count + " groups, " + catalog.KeyCount + " keys, " + catalog.Info.Count + " descriptions ("
                + (catalogWritten ? "written" : "unchanged") + "); commands.js " + commandCount + " commands ("
                + (commandsWritten ? "written" : "unchanged") + ")");
            return 0;
        }

        private static int Scan(string journalDir, string root)
        {
            if (!Directory.Exists(journalDir))
                throw new DirectoryNotFoundException("journal folder not found: " + journalDir);

            int files, lines, rejected;
            var observed = ObservedKeys.Scan(journalDir, ReflectionCatalog(), out files, out lines, out rejected);

            var content = new StringBuilder();
            content.Append("# Journal keys seen in real journal files and unknown to EliteJournalReader (names and types only, no values).\r\n");
            content.Append("# Generated by: update-observed-keys.ps1 (Elite.CatalogGen.exe scan). Merged into catalog.js at build time.\r\n");
            foreach (var line in observed)
                content.Append(line).Append("\r\n");

            bool written = WriteIfChanged(Path.Combine(root, "Elite.CatalogGen", ObservedKeys.FileName), content.ToString());
            Console.WriteLine("Elite.CatalogGen scan: " + files + " files, " + lines + " lines, " + observed.Count + " entries"
                + (rejected > 0 ? ", " + rejected + " rejected (contained the commander name or FID)" : "")
                + " (" + (written ? "written" : "unchanged") + ")");
            return 0;
        }

        private static int ExtractDescriptions(string root)
        {
            var catalog = ReflectionCatalog();
            var observedPath = Path.Combine(root, "Elite.CatalogGen", ObservedKeys.FileName);
            if (File.Exists(observedPath))
                ObservedKeys.Merge(catalog, File.ReadAllLines(observedPath));

            var english = Descriptions.ExtractEnglish(Path.Combine(root, "EliteJournalReader", "Events"), catalog);
            var content = Descriptions.ToJson(english,
                "English comments of EliteJournalReader/Events/*.cs (When written / Parameters), extracted by Elite.CatalogGen.exe descriptions. Source of descriptions-fr.json.");
            bool written = WriteIfChanged(Path.Combine(root, "Elite.CatalogGen", Descriptions.EnglishFile), content);
            Console.WriteLine("Elite.CatalogGen descriptions: " + english.Count(p => p.Key.Count(c => c == '.') == 1) + " events, "
                + english.Count(p => p.Key.Count(c => c == '.') > 1) + " fields (" + (written ? "written" : "unchanged") + ")");
            return 0;
        }

        private static Catalog ReflectionCatalog()
        {
            var catalog = new Catalog();
            StatusCatalog.AddTo(catalog);
            EventCatalog.AddTo(catalog);
            return catalog;
        }

        private static string CatalogJs(Catalog catalog)
        {
            var categoryOrder = Categories.All.Select((c, i) => new { c.Id, i }).ToDictionary(x => x.Id, x => x.i);
            var groups = catalog.Groups
                .Where(g => g.Fields.Count > 0)
                .OrderBy(g => categoryOrder[g.Category])
                .ThenBy(g => g.Label, StringComparer.OrdinalIgnoreCase)
                .ThenBy(g => g.Id, StringComparer.Ordinal)
                .ToList();
            var usedCategories = new HashSet<string>(groups.Select(g => g.Category));

            var sb = new StringBuilder();
            sb.Append("// Generated by Elite.CatalogGen at build time - do not edit (see docs/L2-catalogue.md).\r\n");
            sb.Append("// Key of a field = group.prefix + \".\" + field[0]; field = [path, type] or [path, \"enum\", enum name].\r\n");
            sb.Append("var ELITE_CATALOG = {\r\n");
            sb.Append("\"version\": 1,\r\n");

            sb.Append("\"categories\": [\r\n");
            AppendItems(sb, Categories.All.Where(c => usedCategories.Contains(c.Id))
                .Select(c => new JObject { { "id", c.Id }, { "label", c.Label }, { "emoji", c.Emoji } }));
            sb.Append("],\r\n");

            sb.Append("\"enums\": {\r\n");
            sb.Append(string.Join(",\r\n", catalog.Enums.Select(e => Json(e.Key) + ": " + Json(new JArray(e.Value)))));
            sb.Append("\r\n},\r\n");

            // French descriptions shown by the "i" button: key = event ("journal.FSDJump") or full key
            sb.Append("\"info\": {\r\n");
            sb.Append(string.Join(",\r\n", catalog.Info.Select(i => Json(i.Key) + ": " + Json(i.Value))));
            sb.Append("\r\n},\r\n");

            sb.Append("\"groups\": [\r\n");
            AppendItems(sb, groups.Select(g => new JObject
            {
                { "id", g.Id },
                { "prefix", g.Prefix },
                { "label", g.Label },
                { "category", g.Category },
                { "odyssey", g.Odyssey },
                { "fields", new JArray(g.Fields.Values
                    .OrderBy(f => f.Path, StringComparer.OrdinalIgnoreCase)
                    .ThenBy(f => f.Path, StringComparer.Ordinal)
                    .Select(f => f.EnumName == null ? new JArray(f.Path, f.Type) : new JArray(f.Path, f.Type, f.EnumName))) },
            }));
            sb.Append("]\r\n};\r\n");
            return sb.ToString();
        }

        private static string CommandsJs(List<CommandGroup> groups)
        {
            var sb = new StringBuilder();
            sb.Append("// Generated by Elite.CatalogGen at build time - do not edit (see docs/L2-catalogue.md).\r\n");
            sb.Append("// Keyboard commands: [name for EliteKeys.SendKeypress, label], grouped by binding file.\r\n");
            sb.Append("var ELITE_COMMANDS = {\r\n");
            sb.Append("\"groups\": [\r\n");
            for (int i = 0; i < groups.Count; i++)
            {
                var group = groups[i];
                sb.Append("{\"id\": ").Append(Json(group.Id)).Append(", \"label\": ").Append(Json(group.Label)).Append(", \"commands\": [\r\n");
                AppendItems(sb, group.Commands.Select(c => new JArray(c.Key, c.Value)));
                sb.Append(i + 1 < groups.Count ? "]},\r\n" : "]}\r\n");
            }

            sb.Append("]\r\n};\r\n");
            return sb.ToString();
        }

        private static void AppendItems(StringBuilder sb, IEnumerable<JToken> items)
        {
            var lines = items.Select(Json).ToList();
            if (lines.Count > 0)
                sb.Append(string.Join(",\r\n", lines)).Append("\r\n");
        }

        private static string Json(object value)
        {
            return JsonConvert.SerializeObject(value, JsonSettings);
        }

        private static bool WriteIfChanged(string path, string content)
        {
            if (File.Exists(path) && File.ReadAllText(path) == content)
                return false;

            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, content, new UTF8Encoding(false));
            return true;
        }
    }
}
