// Property inspector of the generic actions ("Donnee" = com.mhwlng.elite.value; Alarm later) - see docs/L5-tiroir.md
// and docs/L6-retours-d5.md. Needs sdtools.common.js, catalog.js and commands.js (generated by Elite.CatalogGen).
// The real settings are the elements of class sdProperty; the view / category / search / field controls only help
// to fill the key of the view being edited (source, source2, source3, source4).
// Keep this file ASCII-only (non-ASCII characters are written as \u escapes).

var GENERIC_ACTION_KINDS = {
    'com.mhwlng.elite.value': 'value'
};

var GENERIC_TYPE_LABELS = {
    'bool': 'oui/non',
    'integer': 'nombre entier',
    'number': 'nombre d\u00e9cimal',
    'text': 'texte',
    'date': 'date/heure',
    'enum': 'liste de valeurs'
};

// tests offered in the image rules, by type of the value (section 6 of the specification)
var GENERIC_NUMBER_OPERATORS = ['isTrue', 'isFalse', 'equals', 'notEquals', 'lt', 'lte', 'gt', 'gte'];
var GENERIC_RULE_OPERATORS = {
    'bool': ['isTrue', 'isFalse', 'equals', 'notEquals'],
    'integer': GENERIC_NUMBER_OPERATORS,
    'number': GENERIC_NUMBER_OPERATORS,
    'text': ['isTrue', 'isFalse', 'equals', 'notEquals'],
    'enum': ['isTrue', 'isFalse', 'equals', 'notEquals'],
    'date': ['isTrue', 'isFalse']
};

var GENERIC_MAX_RESULTS = 100;
var GENERIC_MIN_SEARCH = 2;
var GENERIC_VIEWS = 4;
var GENERIC_RULES = 4;

var genericIndex = null;     // built once from ELITE_CATALOG
var genericActiveView = 1;   // view whose key is being edited
var genericInfoOpen = false; // "i" panel shown

// ---------- catalog index and search (pure functions) ----------

// lower case, without accents: "Train d'atterrissage" -> "train d'atterrissage", "\u00e9" -> "e"
function genericNormalize(text) {
    var value = String(text || '').toLowerCase();
    return value.normalize ? value.normalize('NFD').replace(/[\u0300-\u036f]/g, '') : value;
}

function genericBuildIndex(catalog) {
    var info = catalog.info || {};
    var index = { categories: [], categoryById: {}, groupsByCategory: {}, byKey: {}, entries: [], enums: catalog.enums || {}, info: info };

    catalog.categories.forEach(function (category, order) {
        category.order = order;
        index.categories.push(category);
        index.categoryById[category.id] = category;
        index.groupsByCategory[category.id] = [];
    });

    catalog.groups.forEach(function (group) {
        if (!index.groupsByCategory[group.category])
            return;
        index.groupsByCategory[group.category].push(group);
        var category = index.categoryById[group.category];
        // the description of an event (when it is written) helps the search, not the general text of status.json
        var groupText = group.prefix.indexOf('journal.') === 0 ? (info[group.prefix] || '') : '';
        group.entries = group.fields.map(function (field) {
            var entry = {
                key: group.prefix + '.' + field[0],
                path: field[0],
                type: field[1],
                enumName: field[2] || null,
                group: group,
                category: group.category
            };
            // words found here rank first; words only found in the event description rank second
            entry.ownText = genericNormalize(entry.key + ' ' + group.label + ' ' + (info[entry.key] || ''));
            entry.groupText = genericNormalize(category.label + ' ' + groupText);
            index.byKey[entry.key.toLowerCase()] = entry;
            index.entries.push(entry);
            return entry;
        });
    });

    return index;
}

function genericFindEntry(index, key) {
    if (!index || !key)
        return null;
    return index.byKey[String(key).trim().toLowerCase()] || null;
}

function genericCompare(a, b) {
    a = String(a).toLowerCase();
    b = String(b).toLowerCase();
    return a < b ? -1 : a > b ? 1 : 0;
}

// every word must appear in the key, the group, the category or the French descriptions (case and accents ignored)
function genericSearch(index, text, max) {
    var words = genericNormalize(text).split(/\s+/).filter(function (w) { return w.length > 0; });
    if (words.length === 0)
        return { entries: [], total: 0 };

    var matches = [];
    index.entries.forEach(function (entry) {
        var own = words.every(function (w) { return entry.ownText.indexOf(w) >= 0; });
        if (own || words.every(function (w) { return entry.ownText.indexOf(w) >= 0 || entry.groupText.indexOf(w) >= 0; }))
            matches.push({ entry: entry, score: own ? 0 : 1 });
    });

    // direct matches first, then by category, group and field: entries of a group stay together
    matches.sort(function (a, b) {
        if (a.score !== b.score)
            return a.score - b.score;
        var ca = index.categoryById[a.entry.category].order, cb = index.categoryById[b.entry.category].order;
        if (ca !== cb)
            return ca - cb;
        return genericCompare(a.entry.group.label, b.entry.group.label) || genericCompare(a.entry.group.id, b.entry.group.id)
            || genericCompare(a.entry.path, b.entry.path);
    });

    return { entries: matches.slice(0, max).map(function (m) { return m.entry; }), total: matches.length };
}

function genericGroupLabel(group) {
    return group.label + (group.odyssey ? ' (Odyssey)' : '');
}

function genericTypeLabel(entry) {
    if (/#count$/.test(entry.path))
        return 'nombre d\'\u00e9l\u00e9ments';
    return GENERIC_TYPE_LABELS[entry.type] || entry.type;
}

function genericDescribe(index, key) {
    if (!key)
        return { text: 'Choisissez une donn\u00e9e, ou tapez une cl\u00e9.', warning: false };

    var entry = genericFindEntry(index, key);
    if (!entry)
        return { text: '\u26a0 Cl\u00e9 hors catalogue (saisie manuelle) : elle fonctionnera si le jeu l\'\u00e9crit.', warning: true };

    return { text: 'Type : ' + genericTypeLabel(entry) + ' \u00b7 ' + genericGroupLabel(entry.group), warning: false };
}

// "i" panel: expected values of an entry
function genericExpectedValues(index, entry) {
    if (/#count$/.test(entry.path))
        return 'Nombre entier : nombre d\'\u00e9l\u00e9ments de la liste \u00ab ' + entry.path.replace(/\.#count$/, '') + ' \u00bb.';
    switch (entry.type) {
        case 'bool':
            return 'Oui ou Non (r\u00e8gles d\'ic\u00f4ne \u00ab est vrai \u00bb / \u00ab est faux \u00bb).';
        case 'integer':
            return 'Nombre entier (r\u00e8gles < > = possibles ; facteur et d\u00e9calage pour convertir).';
        case 'number':
            return 'Nombre d\u00e9cimal (r\u00e8gles < > = possibles ; d\u00e9cimales, facteur et d\u00e9calage pour l\'affichage).';
        case 'date':
            return 'Date et heure (affich\u00e9e en heure locale : HH:mm, ou jj/mm HH:mm si ce n\'est pas aujourd\'hui).';
        case 'enum':
            var values = index.enums[entry.enumName] || [];
            return 'Une valeur parmi : ' + values.join(', ') + '.';
        default:
            return 'Texte (r\u00e8gles \u00ab = \u00bb / \u00ab \u2260 \u00bb possibles, sans tenir compte des majuscules).';
    }
}

// ---------- user interface ----------

function genericElement(id) {
    return document.getElementById(id);
}

function genericKeyInput(view) {
    return genericElement('source' + (view === 1 ? '' : view));
}

function genericActiveKey() {
    var input = genericKeyInput(genericActiveView);
    return input ? input.value.trim() : '';
}

function genericInit() {
    if (genericIndex || typeof ELITE_CATALOG === 'undefined' || !genericElement('genericCategory'))
        return;

    genericIndex = genericBuildIndex(ELITE_CATALOG);

    var select = genericElement('genericCategory');
    select.innerHTML = '';
    select.appendChild(genericOption('', '\u2014 choisir une cat\u00e9gorie \u2014'));
    genericIndex.categories.forEach(function (category) {
        var count = genericIndex.groupsByCategory[category.id].reduce(function (n, g) { return n + g.entries.length; }, 0);
        select.appendChild(genericOption(category.id, category.emoji + ' ' + category.label + ' (' + count + ')'));
    });

    genericFillCommands();
    genericFillFields(null);
    genericShowSections();
    genericShowView();
    genericSyncFromSource();
}

function genericOption(value, text) {
    var option = document.createElement('option');
    option.value = value;
    option.textContent = text;
    return option;
}

function genericFieldOption(entry) {
    return genericOption(entry.key, entry.path + ' \u2014 ' + genericTypeLabel(entry));
}

// keyboard commands (commands.js), grouped by binding file, in the command list of every view
function genericFillCommands() {
    if (typeof ELITE_COMMANDS === 'undefined')
        return;

    Array.prototype.forEach.call(document.querySelectorAll('select.generic-command'), function (select) {
        select.innerHTML = '';
        select.appendChild(genericOption('', '\u2014 aucune \u2014'));
        ELITE_COMMANDS.groups.forEach(function (group) {
            var optgroup = document.createElement('optgroup');
            optgroup.label = group.label;
            group.commands.forEach(function (command) {
                var option = genericOption(command[0], command[1]);
                option.title = command[0];
                optgroup.appendChild(option);
            });
            select.appendChild(optgroup);
        });
    });
}

// fills a select with entries grouped by event / status part (placeholder: first line, or none)
function genericFillSelect(select, entries, placeholder) {
    select.innerHTML = '';
    if (placeholder)
        select.appendChild(genericOption('', placeholder));
    if (!entries)
        return;

    var currentGroup = null, optgroup = null;
    entries.forEach(function (entry) {
        if (entry.group !== currentGroup) {
            currentGroup = entry.group;
            optgroup = document.createElement('optgroup');
            optgroup.label = genericGroupLabel(entry.group);
            select.appendChild(optgroup);
        }
        optgroup.appendChild(genericFieldOption(entry));
    });
}

function genericFillFields(entries) {
    genericFillSelect(genericElement('genericField'), entries, '\u2014 choisir une donn\u00e9e \u2014');
}

function genericEntriesOfCategory(categoryId) {
    var entries = [];
    (genericIndex.groupsByCategory[categoryId] || []).forEach(function (group) {
        entries = entries.concat(group.entries);
    });
    return entries;
}

function genericSelectOption(select, key) {
    var wanted = String(key || '').toLowerCase();
    for (var i = 0; i < select.options.length; i++) {
        if (wanted !== '' && select.options[i].value.toLowerCase() === wanted) {
            select.selectedIndex = i;
            return;
        }
    }
    select.selectedIndex = select.options.length > 0 && select.options[0].value === '' ? 0 : -1;
}

// category and field lists positioned on an entry (does not touch the search)
function genericShowEntry(entry) {
    if (entry) {
        genericElement('genericCategory').value = entry.category;
        genericFillFields(genericEntriesOfCategory(entry.category));
        genericSelectOption(genericElement('genericField'), entry.key);
    } else {
        genericElement('genericCategory').value = '';
        genericFillFields(null);
    }
}

// the key of the edited view changed: short description, rule helpers and "i" panel follow
function genericKeyChanged() {
    var info = genericDescribe(genericIndex, genericActiveKey());
    var element = genericElement('genericKeyInfo');
    element.textContent = info.text;
    element.className = 'sdpi-item-value generic-info' + (info.warning ? ' generic-warning' : '');
    genericUpdateRuleHelpers();
    if (genericInfoOpen)
        genericRenderInfo();
}

// called when the settings are loaded or the edited view changes
function genericSyncFromSource() {
    if (!genericIndex)
        return;
    genericElement('genericSearch').value = '';
    genericHideResults();
    genericShowEntry(genericFindEntry(genericIndex, genericActiveKey()));
    genericKeyChanged();
}

// only the fields of the edited view are shown
function genericShowView() {
    var blocks = document.querySelectorAll('[data-view]');
    Array.prototype.forEach.call(blocks, function (block) {
        block.style.display = block.getAttribute('data-view') === String(genericActiveView) ? '' : 'none';
    });
}

function genericViewChanged() {
    genericActiveView = parseInt(genericElement('genericView').value, 10) || 1;
    genericShowView();
    genericSyncFromSource();
}

// chosen by the user: the search is cleared
function genericCategoryChanged() {
    genericElement('genericSearch').value = '';
    genericHideResults();
    var categoryId = genericElement('genericCategory').value;
    genericFillFields(categoryId ? genericEntriesOfCategory(categoryId) : null);
    genericSelectOption(genericElement('genericField'), genericActiveKey());
}

function genericHideResults() {
    genericElement('genericResultsRow').style.display = 'none';
    genericElement('genericSearchInfoRow').style.display = 'none';
}

// the search never clears what is being typed (a first letter used to be erased: search only worked by pasting)
function genericSearchChanged() {
    var text = genericElement('genericSearch').value;
    if (genericNormalize(text).trim().length < GENERIC_MIN_SEARCH) {
        genericHideResults();
        return;
    }

    var result = genericSearch(genericIndex, text, GENERIC_MAX_RESULTS);
    var info = genericElement('genericSearchInfo');
    genericElement('genericSearchInfoRow').style.display = '';
    if (result.total === 0) {
        info.textContent = 'Aucun r\u00e9sultat : essaie un autre mot (fran\u00e7ais ou anglais).';
        genericElement('genericResultsRow').style.display = 'none';
        return;
    }

    info.textContent = result.total + ' r\u00e9sultat(s)' + (result.total > GENERIC_MAX_RESULTS ? ', les ' + GENERIC_MAX_RESULTS + ' premiers affich\u00e9s : pr\u00e9cise ta recherche' : '') + ' \u2014 clique pour choisir.';
    var results = genericElement('genericResults');
    genericFillSelect(results, result.entries, null);
    genericSelectOption(results, genericActiveKey());
    genericElement('genericResultsRow').style.display = '';
}

function genericChooseKey(key) {
    if (!key)
        return;
    genericKeyInput(genericActiveView).value = key;
    genericShowEntry(genericFindEntry(genericIndex, key));
    genericKeyChanged();
    setSettings();
}

function genericResultChosen() {
    var key = genericElement('genericResults').value;
    if (key && key.toLowerCase() !== genericActiveKey().toLowerCase())
        genericChooseKey(key);
}

function genericFieldChanged() {
    genericChooseKey(genericElement('genericField').value);
}

// manual entry of a key (any key, even outside the catalog)
function genericSourceTyped() {
    genericKeyChanged();
    setSettings();
}

// ---------- "i" panel ----------

function genericToggleInfo() {
    genericInfoOpen = !genericInfoOpen;
    genericElement('genericInfoRow').style.display = genericInfoOpen ? '' : 'none';
    if (genericInfoOpen)
        genericRenderInfo();
}

function genericInfoLine(panel, label, text, id) {
    var line = document.createElement('div');
    if (label) {
        var bold = document.createElement('b');
        bold.textContent = label + ' : ';
        line.appendChild(bold);
    }
    var span = document.createElement('span');
    span.textContent = text;
    if (id)
        span.id = id;
    line.appendChild(span);
    panel.appendChild(line);
}

function genericRenderInfo() {
    var panel = genericElement('genericInfoPanel');
    panel.innerHTML = '';
    var key = genericActiveKey();
    if (!key) {
        genericInfoLine(panel, null, 'Choisis d\'abord une donn\u00e9e (vue ' + genericActiveView + ').');
        return;
    }

    var entry = genericFindEntry(genericIndex, key);
    var info = genericIndex.info;
    genericInfoLine(panel, 'Cl\u00e9', key);
    if (!entry) {
        genericInfoLine(panel, null, 'Cl\u00e9 hors catalogue (saisie manuelle) : pas de description. Elle fonctionnera si le jeu l\'\u00e9crit.');
    } else {
        var category = genericIndex.categoryById[entry.category];
        genericInfoLine(panel, 'Cat\u00e9gorie', category.emoji + ' ' + category.label + ' \u00b7 ' + genericGroupLabel(entry.group));
        if (info[entry.group.prefix])
            genericInfoLine(panel, entry.group.prefix.indexOf('journal.') === 0 ? 'Quand' : 'Source', info[entry.group.prefix]);
        genericInfoLine(panel, 'Signification', info[entry.key] || 'pas de description d\u00e9taill\u00e9e pour ce champ.');
        genericInfoLine(panel, 'Valeurs attendues', genericExpectedValues(genericIndex, entry));
    }
    genericInfoLine(panel, 'Valeur actuelle en jeu', '\u2026', 'genericCurrentValue');
    genericRequestValue(key);
}

// asks the plugin for the current value (reply: genericShowValue)
function genericRequestValue(key) {
    var target = genericElement('genericCurrentValue');
    if (typeof websocket === 'undefined' || !websocket || websocket.readyState !== 1) {
        if (target)
            target.textContent = 'disponible seulement dans le logiciel Stream Deck.';
        return;
    }

    websocket.send(JSON.stringify({
        action: actionInfo.action,
        event: 'sendToPlugin',
        context: uuid,
        payload: { genericValueRequest: key, genericView: genericActiveView }
    }));
}

function genericShowValue(reply) {
    var target = genericElement('genericCurrentValue');
    if (!target || String(reply.genericValueKey).toLowerCase() !== genericActiveKey().toLowerCase())
        return;

    if (!reply.genericValuePresent)
        target.textContent = 'pas encore re\u00e7ue (le jeu ne l\'a pas \u00e9crite depuis le d\u00e9marrage du plugin).';
    else
        target.textContent = reply.genericValueRaw + '  \u2192  affich\u00e9 : \u00ab ' + String(reply.genericValueText).replace(/\n/g, ' \u21b5 ') + ' \u00bb';
}

// ---------- image rules ----------

// image rules of the edited view: tests offered according to the type of its value, enum values proposed as operands
function genericUpdateRuleHelpers() {
    if (!genericIndex)
        return;

    var suffix = genericActiveView === 1 ? '' : String(genericActiveView);
    var entry = genericFindEntry(genericIndex, genericActiveKey());
    var allowed = entry ? GENERIC_RULE_OPERATORS[entry.type] : null;
    if (entry && /#count$/.test(entry.path))
        allowed = GENERIC_NUMBER_OPERATORS;
    for (var i = 1; i <= GENERIC_RULES; i++) {
        var select = genericElement('rule' + i + 'Op' + suffix);
        if (!select)
            continue;
        Array.prototype.forEach.call(select.options, function (option) {
            // never disable the current choice, so that a saved rule stays visible
            option.disabled = option.value !== '' && allowed !== null && allowed.indexOf(option.value) < 0 && option.value !== select.value;
        });
    }

    var list = genericElement('genericEnumValues');
    if (!list)
        return;
    list.innerHTML = '';
    var values = [];
    if (entry && entry.type === 'enum' && genericIndex.enums[entry.enumName])
        values = genericIndex.enums[entry.enumName];
    else if (entry && entry.type === 'bool')
        values = ['oui', 'non'];
    values.forEach(function (value) {
        list.appendChild(genericOption(value, value));
    });
}

// sections marked data-actions="value alarm" are shown for these actions only
function genericShowSections() {
    var kind = (typeof actionInfo !== 'undefined' && actionInfo && actionInfo.action) ? GENERIC_ACTION_KINDS[actionInfo.action] : null;
    var sections = document.querySelectorAll('[data-actions]');
    Array.prototype.forEach.call(sections, function (section) {
        var kinds = section.getAttribute('data-actions').split(' ');
        section.style.display = (!kind || kinds.indexOf(kind) >= 0) ? '' : 'none';
    });
}

// sdtools.common.js calls loadConfiguration when the settings arrive (and for sendToPropertyInspector messages).
// The lists (commands...) must exist before the values are loaded; the view / category lists are resynchronised after.
(function () {
    var baseLoadConfiguration = window.loadConfiguration;
    window.loadConfiguration = function (payload) {
        // reply of the plugin to genericRequestValue: not a setting
        if (payload && Object.prototype.hasOwnProperty.call(payload, 'genericValueKey')) {
            genericShowValue(payload);
            return;
        }

        try {
            genericInit();
        } catch (err) {
            console.log('generic.js init: ' + err);
        }

        baseLoadConfiguration(payload);

        try {
            // keys created before "showText" existed show their value; views 2 to 4 created before L5 follow view 1
            if (payload && !Object.prototype.hasOwnProperty.call(payload, 'showText') && genericElement('showText'))
                genericElement('showText').checked = true;
            for (var v = 2; v <= GENERIC_VIEWS; v++) {
                var box = genericElement('showText' + v);
                if (payload && box && !Object.prototype.hasOwnProperty.call(payload, 'showText' + v))
                    box.checked = genericElement('showText').checked;
            }
            genericShowSections();
            genericShowView();
            if (payload && Object.prototype.hasOwnProperty.call(payload, 'source'))
                genericSyncFromSource();
        } catch (err) {
            console.log('generic.js: ' + err);
        }
    };
})();

document.addEventListener('DOMContentLoaded', genericInit);
